### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by revren** [fijiwebdesign/vscode-remote-editor#4]
Using Kubuntu 16.10, VSCode 1.21.1 (20180314,Shell 1.7.9, Node 7.9.0, x64)

command 'remote.editor.connectRemote' not found

**Comment by fijiwebdesign** [comment]
Hi @revren 
Was this on the first install? Did you try reloading vscode after install?

**Comment by revren** [comment]
Hi @fijiwebdesign yes I reloaded immediately after installing, I still have the issue after numerous retries

**Comment by fijiwebdesign** [comment]
@revren I've managed to reproduce this after reinstalling the extension a few times. 

Did you happen to have: https://marketplace.visualstudio.com/items?itemName=carlevans.remote-editor installed at some point? I've seen odd behaviour with the extension using the old code from that one. 

I'll send you an update when I've managed a fix for this.

**Comment by fijiwebdesign** [comment]
@revren The most likely cause of the error is that your `.remote` file is not valid JSON. I will add a fix to show an error message when the `.remote` file cannot be read as JSON in the next release. 

Here is an example `.remote` file:

Note: JSON cannot have trailing ",". Last key/prop must not have ",". 
```
{
  "autoConnect": true,
  "connection": {
    "host": "seedess.com",
    "username": "root",
    "privateKey": "/Users/chandra/.ssh/keys/id_rsa",
    "passphrase": "***",
    "port": "2222"
  },
  "basePath": "/var/www/seedess.com/",
  "ignore": [".git", "src/node_modules"],
  "debug": "*"
}
```

**Comment by revren** [comment]
@fijiwebdesign I didnt have https://marketplace.visualstudio.com/items?itemName=carlevans.remote-editor installed at any point.

Correct my JSON was not valid. Sorry about that, my last key /prop did have a ,", and I failed to close the "" in one of the values.
Having fixed that though I still get eh same error? (I have double checked that I have valid JSON now)

**Comment by revren** [comment]
Actually scrap that! After a restart of VSCode I now get 'syncing..' in the status bar, then all the files are copied!
Thanks so much for your help and sorry that I caused the error in the first place!

**Comment by derence2002** [comment]
This is my .remote file, do take note of the double slash required if you are on Windows.

![image](https://user-images.githubusercontent.com/45398055/50584529-140b6b80-0eab-11e9-9a7a-e8487285d242.png)

**Comment by fijiwebdesign** [comment]
@derence2002 I would suggest using https://github.com/liximomo/vscode-sftp as it's more mature and achieves the same as this package.  I don't have the time to support this package anymore.
